### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by thoughts1053** [nyu-devops-echo/shopcarts#28]
**As a** developer
**I need** a restful api
**So that** I can make http requests to this service

**Assumptions:** 
* API should include CRUD, plus list. query, and action

**Comment by carpetri** [comment]
Hey guys aren't we missing these to requests?
GET on /shopcart/uid/products  (to list all products)
GET on /shopcart/uid/products/pid  (to see the quant)
DELETE on /shopcart/uid/products  (To delete all products)
@thoughts1053 @radhikamattoo

**Comment by thoughts1053** [comment]
Is there a use case for any of these?

You can see all products by getting the cart and remove all products by deleting the cart. Seeing the specific quantity of a specific item in the cart may also not be important.

It's up to us to decide our API. We have all the restful methods, list and action already.

**Comment by radhikamattoo** [comment]
I believe we wanted to focus on the shopcart, not the product, so we implemented CRUD, Action, and Query with the shopcart model in mind.
