### ISSUE TITLE
Adding Products to Shopping Cart

### ISSUE THREAD

**Issue by thoughts1053** [nyu-devops-echo/shopcarts#4]
**As a** customer
**I need** to add products to my shopping cart
**So that** I can purchase them

**Assumptions:** 
* Customer already has a shopping cart in memory
* POST request to `/shopcarts/userid/products`
* If the product already exists, add to the total quantity

**Acceptance Criteria:**
```
Given that my shopping cart already exists
When I make a POST request to /shopcarts/userid/products
And make a GET request to /shopcarts/userid
Then the product I just added should be there
```

**Comment by thoughts1053** [comment]
@carpetri @RegulusXiang @radhikamattoo, so based on reading and I think what professor said in class, `PUT` should send back the whole object and `PATCH` can send just a part of the object to be updated.

Should we make this a `PATCH` method to be more inline with our assumptions or fully replace the current `Shopcart` with what is sent.

**Comment by carpetri** [comment]
I'm not sure here. I'm a little confused now. 
@thoughts1053 Isn't it just a design question ??
I posted a similar question here:
https://github.com/nyu-devops-echo/shopcarts/pull/39

**Comment by radhikamattoo** [comment]
I think it should be a `PATCH`. We definitely don't want to replace the entire Shopcart in memory (wastes time, etc...) and based on how we set up our model, this request modifies/updates a **part** of the object, not the entire thing. Lmk what you think @RegulusXiang @thoughts1053 @carpetri

**Comment by thoughts1053** [comment]
@radhikamattoo I'm leaning towards `PATCH` as well. It'll follow REST more closely, especially if we only want to send part of the cart.

@carpetri this is more of a design question, but it affects the implementation. I'll go and look at your questions on #39 and comment.

**Comment by thoughts1053** [comment]
@radhikamattoo @carpetri Working on this now. I think a `POST` to `/shopcarts/<int:uid>/products` actually makes the most sense. Thoughts?

**Comment by radhikamattoo** [comment]
Ya I can see that working a lot better from a RESTful pov, especially since we define this as adding a single type of product to the shopcart.

**Comment by carpetri** [comment]
Yes, completely! @thoughts1053 @radhikamattoo
